### ISSUE TITLE
I want to get the values of other cells with formulas after updateCell(), What should I do?

### ISSUE THREAD

**Issue by check0927** [sestegra/spreadsheet_decoder#15]
I want to get the values of other cells with formulas after updateCell(), What should I do?

**Comment by sestegra** [comment]
This library only reads data from static file.
If you update a cell that is used within formulas, you have to

1.  Open the file with LibreOffice or Excel to compute the formulas
2. Read again the file

There is no roadmap about integrating business logic of LibreOffice/Excel in this library.
