### ISSUE TITLE
Single quotes (') is replaced by &amp;apos;

### ISSUE THREAD

**Issue by MahMoos** [sestegra/spreadsheet_decoder#16]
Some symbols are replaced with their respective named character reference in the spreadsheet.

**Comment by sestegra** [comment]
"Some symbols" expression is too vague to fix something.

Please provide some sample files to precise your problem.

**Comment by augustinreille** [comment]
Hello,

Expected text was : 

> Prix en ariary MGA
> Repas pour l'anniversaire de mcf avec l'équipe.


![image](https://user-images.githubusercontent.com/32739983/69241204-5915ba80-0baf-11ea-8b6e-c437cae7eb69.png)

File format is xlsx.
