### ISSUE TITLE
excuseme how can i create a new .xlsx file?

### ISSUE THREAD

**Issue by taihangg** [sestegra/spreadsheet_decoder#17]
thanks for the very good lib.
i am try to import/export xlsx files with my flutter app, how can i create a new .xlsx file?
thank you!

**Comment by sestegra** [comment]
This library is only a codec.

If you need to create an empty file, I suggest you to embed a template file in your application and to use it as empty file by copying it.

**Comment by taihangg** [comment]
ok,thank you,that a simple way.
