### ISSUE TITLE
when i send a new created empty xlsx, and then insertRow() or insertColumn()，it will cause exception, because the SpreadsheetTable's default _maxRows and _maxCols is -1 but not 0.

### ISSUE THREAD

**Issue by taihangg** [sestegra/spreadsheet_decoder#18]
thank you!
when i decode a new created empty xlsx, and then insertRow() or insertColumn()，
it will cause a exception, 
because the SpreadsheetTable's _maxRows and _maxCols's initial value is -1, but not 0, 
so the "if (rowIndex < 0 || rowIndex > _tables[sheet]._maxRows)" will always be true.

**Comment by sestegra** [comment]
Without any sample file, I can't reproduce your problem.

**Comment by taihangg** [comment]
sorry,i dont know how to upload the file.
its just an empty xlsx file,created by ms office or wps...

**Comment by DerBasler** [comment]
I think what @taihangg ment is the follwing:
Example file: https://gofile.io/?c=UJ87lu
The follwing Code crashes:
`    decoder.insertRow('1', 0);
    decoder.insertColumn('1', 0);
    decoder.updateCell('1', 0, 0, 'works');
    decoder.insertRow('2', 0);
    decoder.insertColumn('2', 0);
    decoder.updateCell('2', 0, 0, 'works');
    decoder.insertRow('3', 0);
    decoder.insertColumn('3', 0);
    decoder.updateCell('3', 0, 0, 'error');`
The error trace:
`E/flutter (21101): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RangeError: Invalid value: Valid value range is empty: 0
E/flutter (21101): #0      SpreadsheetDecoder.insertRow (package:spreadsheet_decoder/src/spreadsheet.dart:140:7)
E/flutter (21101): #1      XlsxDecoder.insertRow (package:spreadsheet_decoder/src/xlsx.dart:173:11)
E/flutter (21101): #2      HomeScreen.selected (package:budgetberatung/ui/screen/home_screen.dart:116:13)
E/flutter (21101): <asynchronous suspension>
E/flutter (21101): #3      _PopupMenuButtonState.showButtonMenu.<anonymous closure> (package:flutter/src/material/popup_menu.dart)
E/flutter (21101): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (21101): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (21101): #6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (21101): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (21101): #8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (21101): #9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter (21101): #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
E/flutter (21101): #11     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (21101): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21101): #13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (21101): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (21101): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21101): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`

If we insert something in the template.xlsx file on the worksheet "3" then it would work.

**Comment by taihangg** [comment]
@DerBasler maybe its the same reason.
i modified the default value of _maxRows and _maxCols to 0, then it work well.
