### ISSUE TITLE
refreshing the excel sheet after updating some cells

### ISSUE THREAD

**Issue by KarrarMohamed** [sestegra/spreadsheet_decoder#21]
Hello there

I've updated an excel sheet that includes cells that their values depend on those which have been updated (via a formula)

how to force the excel sheet to refresh and reflect the actual values of the cells depending on the updates done via the spreadsheet_decoder;

regards

**Comment by sestegra** [comment]
This feature requires Excel compatible engine.
The only way to re-calculate formulas is to open your document within Excel application.
