### ISSUE TITLE
Exception has occurred. UnsupportedError (Unsupported operation: Spreadsheet format unsupported)

### ISSUE THREAD

**Issue by mlbao** [sestegra/spreadsheet_decoder#23]
when i use this format 'xls' of file then  it gives me the exception

**Comment by sestegra** [comment]
Could you give more context, logs in order to help you ?

**Comment by elloza** [comment]
Same here, the problem is with XLS files, with XLSX it works properly

**Comment by sestegra** [comment]
Ok, I got it now.
XLS format is not supported by this package.
