### ISSUE TITLE
Decoder doesn't work with xml 4.1.0

### ISSUE THREAD

**Issue by RachelleBoerck** [sestegra/spreadsheet_decoder#27]
Hello, 

I run into an issue while using another package that depends on xml ^4.1.0, while this package still runs on ^3.0.0. It would be nice if the xml version of this could be updated.

Here is the Exception that I get:
```
Because flutter_svg >=0.18.0 depends on xml ^4.1.0 and 
spreadsheet_decoder 1.1.0 depends on xml ^3.0.0, flutter_svg >=0.18.0 
is incompatible with spreadsheet_decoder 1.1.0.

And because no versions of spreadsheet_decoder match >1.1.0 <2.0.0, 
flutter_svg >=0.18.0 is incompatible with spreadsheet_decoder ^1.1.0.
```

**Comment by sestegra** [comment]
Your issue is fixed nos. A new package has been released.
