### ISSUE TITLE
Nullsafety branch

### ISSUE THREAD

**Issue by sma** [sestegra/spreadsheet_decoder#28]
I converted this package to NNBD.  I can provide a PR, however publishing will be only possible once `archive` has been converted which still is blocked by `crypto`, which needs to be converted first.

See https://github.com/sma/spreadsheet_decoder/tree/nullsafety

**Comment by sestegra** [comment]
Thank you for working on this topic.

**Comment by sestegra** [comment]
Blocked by https://github.com/dart-lang/crypto/issues/105

**Comment by sestegra** [comment]
I've created and merged a PR from your repository.
#30 is on-going to wait for [archive](https://github.com/brendan-duncan/archive) publication.

**Comment by sestegra** [comment]
Nullsafety package has been published
