### ISSUE TITLE
Can not get dependencies after the last update (0.4.3)

### ISSUE THREAD

**Issue by idrats** [sestegra/spreadsheet_decoder#5]
pub get returns an error:
`Package spreadsheet_decoder has no versions that match >=0.4.3 <0.5.0 derived from:`
What is the reason?

**Comment by sestegra** [comment]
Could you check the output with ```pub -v get``` ?
Basically, the issue is with a conflict with a common package.

**Comment by idrats** [comment]
I've found a conflict with another dependence in xml package. Thank you
