### ISSUE TITLE
'XmlText' is not a subtype of type 'XmlElement' in type cast

### ISSUE THREAD

**Issue by sma** [sestegra/spreadsheet_decoder#6]
I'm getting this exception in Line 288 of `xlsx.dart` when trying to read a .xlsx that has been exported from Apple Numbers. The code expects a `<worksheet>` element as the last child of the loaded document, but the last child is a Text with a `\n`. 

A more robust approach could be to search for the element instead of assuming it is always the last one:
```dart
var workbench = content.findElements('worksheet').first;
```

**Comment by sestegra** [comment]
I would need at least a complete exception log trace or better your file.

**Comment by sma** [comment]
I've attached a minimal XLSX file that demonstrates the problem. If you change line 288 as shown above, it works for me.

[test.xlsx](https://github.com/sestegra/spreadsheet_decoder/files/2893238/test.xlsx)

**Comment by sestegra** [comment]
Issue has been fixed on 1.0.1 release.
Thank you for your support.
